name: Github Action/Workflow Linter

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: ['*']
    paths:
      - '.github/actions/**'
      - '.github/workflows/**'

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install actionlint
        uses: supplypike/setup-bin@1fafb085795af4a3f183502f3a9dffa8f7b83217 # v5.0.0
        with:
          uri: 'https://github.com/rhysd/actionlint/releases/download/v1.7.7/actionlint_1.7.7_linux_amd64.tar.gz'
          name: 'actionlint'
          version: '1.7.7'

      - name: Run actionlint on changed files
        run: |
          echo "::add-matcher::.github/actionlint-matcher.json"

          changed_files=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep "^.github/workflows/.*\.yml$" || echo "")
          if [ -z "$changed_files" ]; then
            echo "No workflow files changed. Skipping lint."
            exit 0
          fi
          echo "Linting the following files:"
          echo "$changed_files"
          echo "$changed_files" | xargs actionlint -color
